apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway
  namespace: mdai
spec:
  # Team overlay: set envFrom so team-specific variable overrides win.
  # envFrom[0] will be parameterized to the team's hub variables ConfigMap.
  envFrom:
    - configMapRef:
        name: mdaihub-team-finops-variables
