apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway
  namespace: mdai
spec:
  config:
    processors:
      transform/redact_pii_fields:
        error_mode: ignore
        log_statements:
        - context: log
          statements:
          - delete_matching_keys(attributes, "${env:FIELDS_TO_REDACT}")
      attributes/hash_pii_fields:
        actions:
        - action: hash
          pattern: ${env:FIELDS_TO_HASH}
      transform/scrub_pii_fields:
        error_mode: propagate
        log_statements:
        - context: log
          statements:
          - replace_pattern(attributes["cc"], "${env:CC_REGEX}", "${env:CC_TEMPLATE}")
          - replace_pattern(attributes["email"], "${env:EMAIL_REGEX}", "${env:EMAIL_TEMPLATE}")
          - replace_pattern(attributes["phone"], "${env:PHONE_REGEX}", "${env:PHONE_TEMPLATE}")
          - replace_pattern(attributes["billing_address"], "${env:ADDRESS_REGEX}",
            "${env:ADDRESS_TEMPLATE}")
          - replace_pattern(attributes["ssn"], "${env:SSN_REGEX}", "${env:SSN_TEMPLATE}")
          - replace_pattern(attributes["name"], "${env:NAME_REGEX}", "${env:NAME_TEMPLATE}")
    service:
      pipelines:
        logs/customer_pipeline:
          processors:
          - transform/scrub_pii_fields
