apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdai-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DecisiveAI/example-argocd.git
    targetRevision: feat/mdai-labs
    path: argocd/apps/dev
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
