apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway
  namespace: mdai
spec:
  config:
    processors:
      filter/dynamic-non-crit-services:
        error_mode: ignore
        logs:
          log_record:
            - '"${env:SERVICE_LIST_REGEX}" != "" and IsMatch(attributes["mdai_service"], "${env:SERVICE_LIST_REGEX}")'
    service:
      pipelines:
        logs/customer_pipeline:
          processors:
            - filter/dynamic-non-crit-services
            - memory_limiter
            - batch
